# Generated by Django 5.1.3 on 2024-11-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('valor_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_de_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'laboratorios',
            },
        ),
    ]
