# Generated by Django 5.1.3 on 2024-11-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipioActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('concentracion', models.CharField(max_length=20)),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_de_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'principios_activos',
            },
        ),
    ]
